### ISSUE TITLE
"Compare by" for boolean histograms shouldn't show a 3-point line

### ISSUE THREAD

**Issue by vdjeric** [mozilla/telemetry-dashboard#130]
These should be bar graphs or multiple pie charts or something else, definitely not a 3-point curve http://bit.ly/1NDvfIn

**Comment by chutten** [comment]
I think a grouped vertical bar graph would be ideal, but MG doesn't support it. I have filed [an issue](https://github.com/mozilla/metrics-graphics/issues/554) on MG to see if it can be added.

As for multiple pies: with the current design it wouldn't be simple to commandeer the selected-key titles to become compared measures. And if the number of compared measures exceeded four, there's no place to put the extra charts.

**Comment by chutten** [comment]
@vdjeric, how about something like this? http://people.mozilla.org/~chutten/media/barGroup.PNG 

Since there's only really one independent measurement (False is 100% - True), I can munge the histograms into a single histogram showing multiple compare values' values. A few tweaks were needed here and there to make the (often long) labels display nicely.

**Comment by vdjeric** [comment]
Yup that would work
