### ISSUE TITLE
Mouse-over label "blinks" (changes style?)

### ISSUE THREAD

**Issue by vdjeric** [mozilla/telemetry-dashboard#144]
STR:
1. load an evo view
2. move the cursor along the curve
3. stop moving the cursor. 

Notice how the label's text style changes subtly as soon as cursor stops moving

**Comment by Uberi** [comment]
* This is caused by CSS transforms on SVG elements.
* When the `transform: translate()` is applied, subpixel rendering is turned off momentarily, which makes the text look bolder,
* It seems to be enabled again after a short delay.
* This seems to be specific to Firefox, but I couldn't find any open issues for this.

**Comment by vdjeric** [comment]
17:13 <&vladan> BenWa: is there a bug for this issue? https://github.com/mozilla/telemetry-dashboard/issues/144#issuecomment-133564113
19:04 <@BenWa> vladan: yes, APZ regression
19:05 <@BenWa> it turns off subpixel AA
