### ISSUE TITLE
Telemetry dashboards should distinguish B2G and Fennec from Linux

### ISSUE THREAD

**Issue by staktrace** [mozilla/telemetry-dashboard#223]
Right now in the telemetry dashboards it's very hard to distinguish B2G and Fennec from Linux desktop. I _believe_ Fennec at least uses the Android API version and so shows up as "Linux 9" or "Linux 23" (and other versions in between) where as desktop Linux shows up as "Linux 3.1" and such. I don't know what B2G is doing, it might be getting lumped in with Linux desktop or Fennec somehow.

**Comment by chutten** [comment]
Distinguishing Fennec is a matter of selecting "Firefox Mobile" from the application filter (instead of "Firefox Desktop"). Trying to select it via the os dropdown is probably going to go awry, as then you'd be looking for Firefox Desktop pings from those Linux versions, which probably don't exist.

As for B2G, let me ask around...

**Comment by chutten** [comment]
Ah-ha! Nightly 44 and earlier have B2G in the application selector. There are so few submissions (57 samples on http://mzl.la/211030k ) that you need to turn off histogram sanitization to see them... but they're there.

Releases that don't have aggregated pings for B2G-identifying applications won't have B2G in the application dropdown, which is why it took me so long to find them :S

**Comment by chutten** [comment]
Annnd, I'm being told that I am incredibly wrong...

It turns out there are some desktop builds of B2G that are contributing those pings, not FxOS on Phones. FxOS has "normal" Telemetry disabled according to :gfritzsche on #telemetry. Instead, the phones send their own JSON to the servers, which is not aggregated for display on t.m.o.

**Comment by staktrace** [comment]
> Distinguishing Fennec is a matter of selecting "Firefox Mobile" from the application filter (instead of 
> "Firefox Desktop"). Trying to select it via the os dropdown is probably going to go awry

It would still be nice to have a separate OS type for them, so that I can do a "compare by target OS" and have Linux separate from Android.

**Comment by staktrace** [comment]
> Instead, the phones send their own JSON to the servers, which is not aggregated for display on t.m.o.

Is it possible to have this data displayed on t.m.o? Or otherwise get access to the raw data?

**Comment by chutten** [comment]
Getting access to the raw data is definitely possible. To query and analyse it, you'll probably want a cluster from https://analysis.telemetry.mozilla.org. I think all you need to do in order to get B2G pings is to specify `app="B2G"` in the `get_pings` call.

To get "compare by target OS" to include Android meaningfully (right now, if you select only the Linuxen with versions > 5 from the dropdown, there are 0 submissions. I think we can probably remove them from the dropdown when the selected application has no submissions for that filter option, but I'm not certain) we'd need to, let's see... Request data for each of the multiple applications, filtered on each of the OS versions... then mux them together into data for the line plot.

And then there would be a plot of... GC_MS based on OS? I'm not sure it would be a meaningful plot. Of course GCs would be slower on phones than on desktop. Feature adoption, similarly, wouldn't be relevant because certain features aren't available on certain applications.

Even the current "compare by target OS" generates a false sense of equivalency between vastly different populations when it comes to hardware, platform API support, and user demographics.

It is probably technically possible to attain in the frontend, but I'm not sure what useful plots you would hope to get from it. Could you provide an example?

**Comment by staktrace** [comment]
I'm more interested in the checkerboarding metrics, don't care about GC_MS. Comparing desktop to mobile would be useful because it can tell us how to tune various prefs to improve the checkerboarding on mobile. I guess it's not hard to just have two tabs open, one with desktop and one with Android and do an old-school compare by rapid tab switch. I'll figure something out.
