### ISSUE TITLE
Add ability to download entirety of keyed histogram

### ISSUE THREAD

**Issue by fbertsch** [mozilla/telemetry-dashboard#259]
Right now, you can only download the keys being displayed.

**Comment by himanish-star** [comment]
@chutten , I would like to work on this issue. May I ?

**Comment by chutten** [comment]
@himanish-star Please do!

**Comment by himanish-star** [comment]
@chutten , could you please explain that in what way do we intend to download the entirety of the histogram. Like an image or something else ?

**Comment by chutten** [comment]
Certainly!

If you view a histogram, even a keyed one, on telemetry.mozilla.org, two buttons appear, labelled "Export CSV" and "Export JSON". This allows users to download CSV/JSON files of the data being displayed so that they can do analysis on the aggregate data themselves, if they want. (Some analysts really really like Excel)

However, if the user's viewing a keyed histogram (like here: https://mzl.la/2B3S5YT) then only the four displayed keys' data is in the resultant exported CSV/JSON file. Keyed histograms can have more than four keys (the one I linked above has about 604 of them), so we'd like the buttons to enable the download of all the keys' data at once.

Does this make sense, @himanish-star ?

**Comment by himanish-star** [comment]
> Does this make sense, @himanish-star ?

Yes, @chutten , Thanks for the explanantion
EDIT: I'll take a day or two to file a PR
