### ISSUE TITLE
factor in gpu-process crashes into the crash dashboard

### ISSUE THREAD

**Issue by philipp-sumo** [mozilla/telemetry-dashboard#291]
firefox 53 introduces a new gpu process ("quantum compositor") - we should find a way to incorporate that into the crash dashboard. 

at the moment it looks like in socorro there is a rather small number of those reports, so maybe we can just count those crashes into the content crash rate (also see issue #290), as those types of crashes might feel similar to affected users, and add a note about this on the dashboard.

**Comment by chutten** [comment]
The dashboard as it stands is set to show rates instead of counts, so it'll require a little more effort to treat gpu crashes as a count. Shouldn't be too terrible.

That being said, I'm not sure that counts give us anything better than rates. So long as the proportion of the population getting gpu processes (and, thus, gpu crashes) is a representative %ge of the overall population, then it'll likely still follow the same weekly/seasonal ups and downs that the "per-kilo-usage-hour" rate was designed to normalize.

I'll experiment a bit here and see what it looks like.

**Comment by philipp-sumo** [comment]
sorry if i haven't expressed myself clearly. i'm not interested in a count per se, but just wanted to raise the issue that gpu process crashes should be factored into the rates "somehow". i think they could be treated as part of the content crash rates for example...

**Comment by chutten** [comment]
No, no, it's fine. We each have our own vocabulary with our own meanings for words. For me a "count" is not useful un-normalized (I've actually [blogged on the subject](https://chuttenblog.wordpress.com/?p=2493)) and is distinct from a "rate".

I can add gpu_crashes per thousand usage hours as a row with little problems, once I clear up some [pending issues](https://github.com/mozilla/telemetry-dashboard/pull/282) first.

**Comment by chutten** [comment]
Give it a go now? How's it look?

**Comment by philipp-sumo** [comment]
thank you!
