### ISSUE TITLE
Weird e10s option showing up on telemetry.m.o

### ISSUE THREAD

**Issue by staktrace** [mozilla/telemetry-dashboard#297]
1. Go to https://mzl.la/2mjZiP7
2. Click on the "any e10s setting" part of the query

Expected: 2 options, "e10s" and "no e10s"
Actual: there is a third option, a very large negative number

**Comment by fbertsch** [comment]
Okay so this was a tiny amount of data - at most 3 pings. So I'm not sure it's worth worrying about.

However, it might make sense to add expected values for our dimensions to prevent this sort of weirdness in the future. E.g. only allow True/False for e10sEnabled, and record counts of other values during aggregation so we can make sure nothing bad has been missed.

OTOH aggregates should contain everything our data does, and doing the above could lead to some bad backfill situations (if there ended up being a significant chunk of pings we didn't process because some value changed and didn't match).

**Comment by chutten** [comment]
Instead of limiting options or limiting aggregates, maybe we can focus on limiting value lengths. Certainly that's something we can do on the dashboard side (max-width that popup). 

Maybe telemetry.js' sanitized() should erase unpopular options as well as unpopular entries...

**Comment by fbertsch** [comment]
This option comes from `https://aggregates.telemetry.mozilla.org/filters/?channel=release&version=50`. We'd have to push numbers into the get_filter_options, which is actually a separate table in the database with all filter options for a certain channel/version (and no counts)... wouldn't be very easy.

max-width sounds like a good thing though :)

**Comment by chutten** [comment]
Alrighty, we can fix this dashboard-side with a presentation-level fix. Not a big priority, looks like, though. But a good first bug.

**Comment by chutten** [comment]
Cloned to https://bugzilla.mozilla.org/show_bug.cgi?id=1396890 so it can appear in Bugs Ahoy
