### ISSUE TITLE
Remove release data from measurements dashboard

### ISSUE THREAD

**Issue by georgf** [mozilla/telemetry-dashboard#399]
Looking at [release probes](https://mzl.la/2CaAT9i) now is confusing.
Where are we with the release data now?
Can we make the status more clear to users?

Options i can think of:
- We could remove release completely from the dashboard UI.
- Show a message when selecting release (awkward?)

**Comment by chutten** [comment]
This may or may not be covered by https://bugzilla.mozilla.org/show_bug.cgi?id=1411303

**Comment by Sylvia23** [comment]
Hi there,
 I would like to work for this.

**Comment by chutten** [comment]
@Sylvia23 Great, please go ahead!

What needs to be done is to prevent any "release" channel+version combinations from appearing in the multiselect on the Measurement and Evolution dashboard pages. These views have never been particularly useful (the data came from a self-selected sub-population) and since release 58 anyone claiming they're sending data from that release is likely lying :)

(( For anyone coming across this Issue and wondering what happened to the data, don't worry it is still there :) Anyone wishing to peruse the statistically non-representative historical data will still be able to access it via telemetry.js for the time being. (we are preparing better release aggregates for later this year) ))

**Comment by Sylvia23** [comment]
@chutten , so basically I have to remove the "release" channel from the UI. In both Measurement and Evolution Dashboard, "release" could be seen in the dropdown menu.
I am looking into the codebase (mainly dist.js, evo.js and dashboard.js) to implement this as it seems to require in-depth knowledge of working of code. 
Any advice on where and how to get started with the implementation is also most welcome!
Thanks.

**Comment by chutten** [comment]
@Sylvia23 The method for generating the options in the channel+version dropdown is `getHumanReadableOptions` when called with the `channelVersion` argument (as is done in evo.js around line 42). If you forbid that method from returning anything with "release" in it, I think that would be a useful starting place.

**Comment by Sylvia23** [comment]
Hi @chutten, I have successfully removed the "release" channel and its versions from the drop-down menu of both Measurement and Evolution Dashboard.
Thanks for the guidance.
Can you please review the PR.
