### ISSUE TITLE
Use button group for top-right dashboard buttons

### ISSUE THREAD

**Issue by georgf** [mozilla/telemetry-dashboard#440]
In #424 Erin suggested a nice visual improvement of using a button group for the top right buttons in the measurements dashboard.
We should do that.

**Comment by ecomerford** [comment]
Hi @georgf @chutten! Thoughts on these [updates](https://ecomerford.github.io/telemetry-dashboard/new-pipeline/dist.html#) so far? 

My main concern now is that the button expands when clicked, which doesn't look great. 

I think I would have to dig into the css to change the padding on the input box in order to fix this. Does that sound right? And if so, should I do that?

Thanks! :)

**Comment by georgf** [comment]
Nice, it's working!

Visually, it would be great if the button does not expand vertically.
Right, we could either adjust the CSS or consider adding the input as a separate button to the right, like suggested in #454.

**Comment by ecomerford** [comment]
Oh, I see! For some reason I read all of that as being within the anchor tag, but I understand what you intended now. I'll work on making it appear as a new button when clicked. Thanks!

**Comment by gargshruti30** [comment]
@chutten @georgf  is this issue still open ? Can I work on this issue ?

**Comment by chutten** [comment]
@gargshruti30 this Issue is assigned to ecomerford.

**Comment by georgf** [comment]
This was fixed by #483.
