### ISSUE TITLE
Stats tab doesn't display if channel is set to "any"

### ISSUE THREAD

**Issue by chutten** [mozilla/telemetry-dashboard#459]
If the channel is set to "any", the stats tab won't load properly due and will log

```console
TypeError: data[0] is undefined
```

This is because `gChannelInfo.any.versions` is empty, which appears to be because `extractChannelInfos` doesn't put any version information in.

We should handle this somehow... but I'm not sure how. @georgf, do you have an idea about how this could be fixed ideally?

**Comment by georgf** [comment]
So this is the bug that causes #441!
When clicking the stats view button, we start our code path [here](https://github.com/mozilla/telemetry-dashboard/blob/f5441936e43347f743ac86d19f3c803d689bcd11/probe-dictionary/explore.js#L159).
Clicking on the error in the console should take us to where specifically things are going wrong.

The actual problem here might be in `showSearchOnlyFilters()`. When checking `#select-channel`, we should not set it to the value `"any"` (and not check for that value).

**Comment by Sylvia23** [comment]
@chutten @georgf Can I look into this ?

**Comment by chutten** [comment]
Please do!

**Comment by Sylvia23** [comment]
@chutten, Here, when we click `stats` after checking `any` channel, then what should be displayed?

**Comment by chutten** [comment]
@Sylvia23 One of:
1) an informative error message, asking the user to select a branch
2) Some default branch's display (say, release's)
3) counts of recorded/new/expired probes in all channels

Ideally, I would prefer 3. But 2 would do as well.

**Comment by Sylvia23** [comment]
@chutten , You mean the data of all three channels should be displayed with all the probes.  For this, a total of nine histograms will be shown (three channels with three probes for each). Is this desired?

Alternatively, we can show a default branch's display (say, release's) along with an error message. Does that look good?

Please suggest.

**Comment by Sylvia23** [comment]
Though, the implementation of point 2 suggested by you is up in the PR #471 . Can you review if it looks good?
Thanks!

**Comment by chutten** [comment]
For 3 I was hoping it would show a combined view. One chart with the sum of all channels being shown.

But 2 works as well. I've reviewed #471 and have some comments.
