### ISSUE TITLE
Crashes- Once the date is changed the populated graph should disappear.

### ISSUE THREAD

**Issue by gargshruti30** [mozilla/telemetry-dashboard#486]
https://telemetry.mozilla.org/crashes/
When a date is selected and we click on a crash cell to generate a graph and after that when the date is changed the populated graph should disappear and that option to "Click on a crash cell to populate graph" should come.
@chutten @georgf Can I work on this issue ?
![screenshot from 2018-03-20 19-33-03](https://user-images.githubusercontent.com/34654829/37659455-1096b544-2c76-11e8-8311-b838444b4ff8.png)

**Comment by Sylvia23** [comment]
The message `Click on a crash cell to populate graph` comes when we open the page for the first time or reload the page. I think that's fine because the user would know that he has to click on the cell to populate the graph. Now, it doesn't matter whether he is `changing the date` or `changing the channel cell`, the process/instruction remains same.
Does that sound right?  @gargshruti30 @chutten @georgf

**Comment by gargshruti30** [comment]
@Sylvia23 The message 'Click on a crash cell to populate graph' is displayed till the time the user clicks a Crash cell and the graph is generated and when the user changes the date the graph of the previous crash cell exists. So I think it should not be displayed instead the message should again be displayed.

**Comment by chutten** [comment]
It is intended that the selected cell remain selected as the user clicks on different dates in the graph. This is to keep the graph from disappearing out from under the user's mouse each time they click.

The idea is that a given user of tmo/crashes is interested in a particular type of crash. Maybe Release M+C-S is their interest, and they may want to click on different parts of the graph to see the full breakdown at different inflection points on the graph.

**Comment by gargshruti30** [comment]
Okay.
Thanks for the information.
