### ISSUE TITLE
issue in probe dictionary 'recorded' settings

### ISSUE THREAD

**Issue by shradha-khapra** [mozilla/telemetry-dashboard#494]
In the probe dictionary section when the 'recorded' drop-down is set to EXPIRED it displays the expired probes but when the drop-down is set to NEW it always shows all the probes including the expired ones.
Is it a bug or are all the probes new?

**Comment by chutten** [comment]
Let's take an example. Here's an example of NEW: https://telemetry.mozilla.org/probe-dictionary/?search=&searchtype=in_any&optout=true&channel=release&constraint=new_in&version=any&view=stats-view

I take this to mean that we added around 110 probes in Firefox 31.

For EXPIRED, here's the link: https://telemetry.mozilla.org/probe-dictionary/?search=&searchtype=in_any&optout=true&channel=release&constraint=is_expired&version=any&view=stats-view

I take this to mean that only a few probes expired in Firefox 33.

**Comment by shradha-khapra** [comment]
@chutten  I believe you are correct but I suppose due to some error in searching it is displaying all probes when new probes are clicked and not excluding the expired ones.

**Comment by chutten** [comment]
If that's so, then that's a bug indeed.

**Comment by georgf** [comment]
@shradha-khapra, thanks for raising this, i'm trying to understand what specifically the issue is.

When looking at a specific channel and version, [like here](https://telemetry.mozilla.org/probe-dictionary/?channel=nightly&version=61), this seems to work fine.

I suppose you mean the situation where "version" is set to "any", like [here](https://telemetry.mozilla.org/probe-dictionary/?constraint=new_in)?
This is basically searching all probes that "expired in any Firefox version" and probes that "were new in any Firefox version".
What results would you expect?

**Comment by georgf** [comment]
Closing this for now due to inactivity. Happy to reopen this though if there is an underlying issue here!
