### ISSUE TITLE
Update background hang reporting link

### ISSUE THREAD

**Issue by georgf** [mozilla/telemetry-dashboard#557]
The background hang reporting link on the portal page now redirects to [arewesmoothyet.com](http://arewesmoothyet.com/).
We should update it.

**Comment by chutten** [comment]
Right now it is pointing at squarewave, so let's change the link

**Comment by abhinandan1995** [comment]
Ready to take this up. Can you let me know where it should point to?

**Comment by chutten** [comment]
@abhinandan1995 It should point to https://arewesmoothyet.com/

Please let me know if you have any questions.

**Comment by abhinandan1995** [comment]
@chutten 
I do have a question. And it's regarding the permissions things.
So i cloned the repo. started out on new branch <issue-557> from the latest code. Made the required changes. Committed the changes but when i tried to push the code it gave me the error:
Permission to mozilla/telemetry-dashboard.git denied to abhinandan1995.

**Comment by badboy** [comment]
@abhinandan1995 In order to submit your changes as a Pull Request you first need to [fork this repository](https://help.github.com/articles/fork-a-repo/) and push your changes to your own fork. You can then create a Pull Request against mozilla/telemetry-dashboard in order for us to pull it in.

If it's only a small change you can do all  those steps right in the web UI of GitHub. [Browse to the file](https://github.com/mozilla/telemetry-dashboard/blob/gh-pages/index.html) and look for the "pen" icon right next to the "Copy", "Raw", ... buttons. If you click that you will get to an editor view. Make your changes, scroll down and fill in the commit details, then hit "Propose file change" and it will open the PR.

**Comment by abhinandan1995** [comment]
@badboy Thanks for the help. Okay I've made the changes and gave a PR. @chutten Anything else that i could look into. There were some issues that i was looking into and some of them seem to be fixed although their state is open.

**Comment by chutten** [comment]
#558 is available if you're looking for something like that. Otherwise, #536 is an odd one which might require a little investigation.
